### ISSUE TITLE
wpcli:uploads:rsync:pull no such file or directory

### ISSUE THREAD

**Issue by Julhol-droid** [lavmeiker/capistrano-wpcli#50]
Hello I have a Wordpress Bedrock Setup and deploy it to my staging server + run composer install.

This all works fine.

But when i want to rsync my uploads i get this error:
```
$ bundle exec cap staging wpcli:uploads:rsync:pull --trace
** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
[Deprecation Notice] Future versions of Capistrano will not load the Git SCM
plugin by default. To silence this deprecation warning, add the following to
your Capfile after `require "capistrano/deploy"`:

    require "capistrano/scm/git"
    install_plugin Capistrano::SCM::Git

** Invoke wpcli:uploads:rsync:pull (first_time)
** Execute wpcli:uploads:rsync:pull

00:00 wpcli:uploads:rsync:pull
      01 rsync -avz --rsh=ssh --progress -e 'ssh -p 22' myuser.at@xx.xxx.xxx.xxx:/var/www/vhosts/myuser.at/br-be.staging.myuser.at/wp_bedrock/shared/web/app/uploads/ web/app/uploads/
cap aborted!
Errno::ENOENT: No such file or directory - ( export PATH="/usr/bin:/var/www/vhosts/myuser.at/.phpenv/shims:/opt/plesk/phpenv/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/opt/plesk/node/16/bin" WP_ENV="staging" ; /usr/bin/env rsync -avz --rsh=ssh --progress -e 'ssh -p 22' myuser.at@xx.xxx.xxx.xxx:/var/www/vhosts/myuser.at/br-be.staging.myuser.at/wp_bedrock/shared/web/app/uploads/ web/app/uploads/ )
C:/Ruby32-x64/lib/ruby/3.2.0/open3.rb:222:in `spawn'
C:/Ruby32-x64/lib/ruby/3.2.0/open3.rb:222:in `popen_run'
C:/Ruby32-x64/lib/ruby/3.2.0/open3.rb:103:in `popen3'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sshkit-1.21.5/lib/sshkit/backends/local.rb:44:in `execute_command'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
<internal:kernel>:90:in `tap'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:80:in `execute'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/capistrano-wpcli-0.1.5/lib/capistrano/tasks/wpuploads.rake:43:in `block (6 levels) in <top (required)>'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:31:in `run'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/capistrano-3.18.0/lib/capistrano/dsl.rb:76:in `run_locally'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/capistrano-wpcli-0.1.5/lib/capistrano/tasks/wpuploads.rake:39:in `block (5 levels) in <top (required)>'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/capistrano-wpcli-0.1.5/lib/capistrano/tasks/wpuploads.rake:38:in `each'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/capistrano-wpcli-0.1.5/lib/capistrano/tasks/wpuploads.rake:38:in `block (4 levels) in <top (required)>'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/airbrussh-1.5.0/lib/airbrussh/rake/context.rb:58:in `execute'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/capistrano-3.18.0/lib/capistrano/application.rb:14:in `run'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/capistrano-3.18.0/bin/cap:3:in `<top (required)>'
C:/Ruby32-x64/bin/cap:25:in `load'
C:/Ruby32-x64/bin/cap:25:in `<main>'
Tasks: TOP => wpcli:uploads:rsync:pull
```

Maybe the reason for this is that i am on windows and do not have rsync installed.
The path for rsync /var/www/vhosts/myuser.at/br-be.staging.myuser.at/wp_bedrock/shared/web/app/uploads/ exists on the remote server and web/app/uploads also exists on my local machine.
Running 'bundle exec cap staging wpcli:run["core version"]' works great.

Any ideas would be great. Thanks in advance

**Comment by Julhol-droid** [comment]
Well it seems to be because of windows.
I now use WSL for this tasks which now worked.

However I had to install the build-essential to run "bundle install" in first place, if somebody faces the same issue as me.
